-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 21:41:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema sistemaalunos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemaalunos` ;

-- -----------------------------------------------------
-- Schema sistemaalunos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaalunos` DEFAULT CHARACTER SET utf8 ;
USE `sistemaalunos` ;

-- -----------------------------------------------------
-- Table `sistemaalunos`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaalunos`.`Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `AlunoNome` VARCHAR(45) NOT NULL,
  `RaAluno` INT NOT NULL,
  `CpfAluno` INT NOT NULL,
  `RgAluno` VARCHAR(45) NOT NULL,
  `TelefoneAluno` INT NOT NULL,
  `EndRua` VARCHAR(45) NOT NULL,
  `EndNumero` INT NOT NULL,
  `EndComplemento` VARCHAR(45) NULL,
  `EndBairro` VARCHAR(45) NOT NULL,
  `EndCidade` VARCHAR(45) NOT NULL,
  `EndEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlunos`))
ENGINE = InnoDB;


insert into alunos values (0, 'Marlon', 55, 5555, 34211010, 'rosas', 123, 'complemento', 'Centro', 'Frutal', 'MG')

